services:
  bot:
    build: .
    image: johncons/discord-channel-bot:latest
    container_name: discord-channel-bot
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
